### ISSUE TITLE
Doesn't build with GHC-8.8

### ISSUE THREAD

**Issue by phadej** [jswebtools/language-ecmascript#85]
I made revisions ([about revisions](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md)) to correct version bounds https://hackage.haskell.org/package/language-ecmascript-0.19/revisions/

```
src/Language/ECMAScript3/Parser.hs:797:31: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: MonadIO m
        bound by the type signature for:
                   parseJavaScriptFromFile :: forall (m :: * -> *).
                                              MonadIO m =>
                                              String -> m [Statement SourcePos]
        at src/Language/ECMAScript3/Parser.hs:(792,1)-(793,50)
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            parseJavaScriptFromFile :: forall (m :: * -> *).
                                       MonadIO m =>
                                       String -> m [Statement SourcePos]
    • In the expression: fail (show err)
      In a case alternative: Left err -> fail (show err)
      In a stmt of a 'do' block:
        case parse parseScript filename chars of
          Left err -> fail (show err)
          Right (Script _ stmts) -> return stmts
    |
797 |     Left err               -> fail (show err)
    | 
```

**Comment by achudnov** [comment]
I haven't followed the recent GHC/base versions, but, judging by the error message, I'm assuming `fail` is no longer part of the definition of `Monad`?

**Comment by phadej** [comment]
If I don't miss some other issues: the easiest, and non (strictly) breaking change is to change

```haskell
-- | Read a JavaScript program from file an parse it into a list of
-- statements
parseJavaScriptFromFile :: MonadIO m => String -- ^ file name
                        -> m [Statement SourcePos]
parseJavaScriptFromFile filename = do
  chars <- liftIO $ readFile filename
  case parse parseScript filename chars of
    Left err               -> fail (show err)
    Right (Script _ stmts) -> return stmts
```

into

```haskell
-- | Read a JavaScript program from file an parse it into a list of
-- statements
parseJavaScriptFromFile :: MonadIO m => String -- ^ file name
                        -> m [Statement SourcePos]
parseJavaScriptFromFile filename = do
  chars <- liftIO $ readFile filename
  case parse parseScript filename chars of
    Left err               -> liftIO (throwIO (userError (show err))) -- or some custom exception
    Right (Script _ stmts) -> return stmts
```

fail for `IO` throws `userError` anyway, so the behavior will be quite the same.

**Comment by achudnov** [comment]
The change looks good to me. Could you submit a PR with it? If not I'll patch and release myself later today.

**Comment by phadej** [comment]
Sorry, but I have no time to spare more than to just report. For me the proper bounds on Hackage is enough, and that's done.

**Comment by swamp-agr** [comment]
Hi @achudnov, 

Could you please publish new version on Hackage?

**Comment by achudnov** [comment]
I’ll try to do it this weekend. The Travis config is broken, so I’ve been unable to test on earlier compiler versions.

**Comment by achudnov** [comment]
@dmjio for assistance with the Travis config.

**Comment by achudnov** [comment]
Fixed in 0.19.0.1 on Hackage
